services:
  client:
    build:
      context: game-client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports: 
      - "4173:4173"
  server:
    build:
      context: game-server
      dockerfile: Dockerfile
    depends_on:
      - database
    ports: 
      - "3000:3000"
  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: game
